<?php 
return array(
	array(
		'args'    => array('slug' => 'training', 'id' => 24),
		'url'     => routelink('category', array('slug' => 'training')),
		'type'    => 'category',
		'name'    => 'Training',
		'submenu' => array(
			array(
				'args' => array('slug' => 'strength-training', 'id' => 118),
				'url'  => routelink('category', array('slug' => 'strength-training')),
				'type' => 'category',
				'name' => 'Strength',
			),
			array(
				'args' => array('slug' => 'get-faster', 'id' => 119),
				'url'  => routelink('category', array('slug' => 'get-faster')),
				'type' => 'category',
				'name' => 'Get Faster',
			),
			array(
				'args' => array('view' => 'conditioning'),
				'url'  => 'http://conditioning.stack.com/',
				'type' => 'static',
				'name' => 'Conditioning',
			),
		),
	),
	array(
		'args'    => array('slug' => 'training', 'id' => 24),
		'url'     => routelink('category', array('slug' => 'training')),
		'type'    => 'category',
		'name'    => 'Nutrition',
		'submenu' => array(
			array(
				'args' => array('slug' => 'strength-training', 'id' => 118),
				'url'  => routelink('category', array('slug' => 'strength-training')),
				'type' => 'category',
				'name' => 'Strength',
			),
			array(
				'args' => array('slug' => 'get-faster', 'id' => 119),
				'url'  => routelink('category', array('slug' => 'get-faster')),
				'type' => 'category',
				'name' => 'Get Faster',
			),
			array(
				'args' => array('view' => 'conditioning'),
				'url'  => 'http://conditioning.stack.com/',
				'type' => 'static',
				'name' => 'Conditioning',
			),
		),
	),
	array(
		'args'    => array('slug' => 'training', 'id' => 24),
		'url'     => routelink('category', array('slug' => 'training')),
		'type'    => 'category',
		'name'    => 'Skills',
		'submenu' => array(
			array(
				'args' => array('slug' => 'strength-training', 'id' => 118),
				'url'  => routelink('category', array('slug' => 'strength-training')),
				'type' => 'category',
				'name' => 'Strength',
			),
			array(
				'args' => array('slug' => 'get-faster', 'id' => 119),
				'url'  => routelink('category', array('slug' => 'get-faster')),
				'type' => 'category',
				'name' => 'Get Faster',
			),
			array(
				'args' => array('view' => 'conditioning'),
				'url'  => 'http://conditioning.stack.com/',
				'type' => 'static',
				'name' => 'Conditioning',
			),
		),
	),
	array(
		'args'    => array('slug' => 'training', 'id' => 24),
		'url'     => routelink('category', array('slug' => 'training')),
		'type'    => 'category',
		'name'    => 'Gear',
		'submenu' => array(
			array(
				'args' => array('slug' => 'strength-training', 'id' => 118),
				'url'  => routelink('category', array('slug' => 'strength-training')),
				'type' => 'category',
				'name' => 'Strength',
			),
			array(
				'args' => array('slug' => 'get-faster', 'id' => 119),
				'url'  => routelink('category', array('slug' => 'get-faster')),
				'type' => 'category',
				'name' => 'Get Faster',
			),
			array(
				'args' => array('view' => 'conditioning'),
				'url'  => 'http://conditioning.stack.com/',
				'type' => 'static',
				'name' => 'Conditioning',
			),
		),
	),
	array(
		'args'    => array('slug' => 'training', 'id' => 24),
		'url'     => routelink('category', array('slug' => 'training')),
		'type'    => 'category',
		'name'    => 'Lifestyle',
		'submenu' => array(
			array(
				'args' => array('slug' => 'strength-training', 'id' => 118),
				'url'  => routelink('category', array('slug' => 'strength-training')),
				'type' => 'category',
				'name' => 'Strength',
			),
			array(
				'args' => array('slug' => 'get-faster', 'id' => 119),
				'url'  => routelink('category', array('slug' => 'get-faster')),
				'type' => 'category',
				'name' => 'Get Faster',
			),
			array(
				'args' => array('view' => 'conditioning'),
				'url'  => 'http://conditioning.stack.com/',
				'type' => 'static',
				'name' => 'Conditioning',
			),
		),
	),
	array(
		'args'    => array('slug' => 'sports'),
		'url'     => routelink('sport', array('slug' => '')),
		'type'    => 'sport',
		'name'    => 'Sports',
		'submenu' => array(
			array(
				'args' => array('slug' => 'football'),
				'url'  => routelink('sport', array('slug' => 'football')),
				'type' => 'sport',
				'name' => 'Football',
			),
			array(
				'args' => array('slug' => 'basketball'),
				'url'  => routelink('sport', array('slug' => 'basketball')),
				'type' => 'sport',
				'name' => 'Basketball Training',
			),
			array(
				'args' => array('slug' => 'baseball'),
				'url'  => routelink('sport', array('slug' => 'baseball')),
				'type' => 'sport',
				'name' => 'Baseball',
			),
			array(
				'args' => array('slug' => 'hockey'),
				'url'  => routelink('sport', array('slug' => 'hockey')),
				'type' => 'sport',
				'name' => 'Hockey',
			),
			array(
				'args' => array('slug' => 'soccer'),
				'url'  => routelink('sport', array('slug' => 'soccer')),
				'type' => 'sport',
				'name' => 'Soccer',
			),
			array(
				'args' => array('slug' => 'track-and-field'),
				'url'  => routelink('sport', array('slug' => 'track-and-field')),
				'type' => 'sport',
				'name' => 'Track &amp; Field',
			),
			array(
				'args' => array('slug' => 'cross-country'),
				'url'  => routelink('sport', array('slug' => 'cross-country')),
				'type' => 'sport',
				'name' => 'Cross Country',
			),
			array(
				'args' => array('slug' => 'yoga'),
				'url'  => routelink('sport', array('slug' => 'yoga')),
				'type' => 'sport',
				'name' => 'Yoga',
			),
			array(
				'args' => array('slug' => 'sports'),
				'url'  => routelink('sport', array('slug' => 'sports')),
				'type' => 'sport',
				'name' => 'More',
			),
		),
	),
	array(
		'args'    => array('slug' => 'videos'),
		'url'     => routelink('videos', array('slug' => '')),
		'type'    => 'videos',
		'name'    => 'Videos',
		'submenu' => array(
			array(
				'args' => array('slug' => 'michael-johnson-performance'),
				'url'  => routelink('videos', array('slug' => 'michael-johnson-performance')),
				'type' => 'videos',
				'name' => 'Michael Johnson Performance',
			),
			array(
				'args' => array('slug' => 'new-balance-baseball'),
				'url'  => routelink('videos', array('slug' => 'new-balance-baseball')),
				'type' => 'videos',
				'name' => 'New Balance Baseball',
			),
			array(
				'args' => array('slug' => 'elite-performance-mike-boyle'),
				'url'  => routelink('videos', array('slug' => 'elite-performance-mike-boyle')),
				'type' => 'videos',
				'name' => 'STACK Elite Performance',
			),
			array(
				'args' => array('slug' => 'stack-fitness-weekly'),
				'url'  => routelink('videos', array('slug' => 'stack-fitness-weekly')),
				'type' => 'videos',
				'name' => 'STACK Fitness Weekly',
			),
			array(
				'args' => array('slug' => 'todd-durkin-workouts'),			
				'url'  => routelink('videos', array('slug' => 'todd-durkin-workouts')),
				'type' => 'videos',
				'name' => 'Todd Durkin\'s World-Class Workouts',
			),
			array(
				'args' => array('slug' => 'path-to-the-pros-2015'),
				'url'  => routelink('videos', array('slug' => 'path-to-the-pros-2015')),
				'type' => 'videos',
				'name' => 'Path to the Pros: 2015',
			),
		),
	),
	array(
		'args' => array('slug' => 'guided'),
		'url'  => routelink('search', array('slug' => 'guided')),
		'type' => 'static',
		'name' => 'Guided Search',
	),
);